// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wedding.gift.Infra.Implementations.DataContext;

#nullable disable

namespace wedding.gift.Infra.Implementations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("wedding.gift.Domain.Model.Entities.Contribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ContributorName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("GiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("GiftId");

                    b.ToTable("Contributions");
                });

            modelBuilder.Entity("wedding.gift.Domain.Model.Entities.Gift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Gifts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cbb2ebce-0130-4acc-aebc-054ca72cbfca"),
                            Available = true,
                            Category = "Cozinha",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Conjunto com 5 panelas em inox para o dia a dia.",
                            ImageUrl = "https://images.example.com/panelas-inox.jpg",
                            Price = 899.90m,
                            Title = "Jogo de Panelas Inox",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b8db2a9c-ee89-41f7-b50a-6d9fa59e34fc"),
                            Available = true,
                            Category = "Eletrodomésticos",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Liquidificador potente com copo de vidro.",
                            ImageUrl = "https://images.example.com/liquidificador.jpg",
                            Price = 459.90m,
                            Title = "Liquidificador 1200W",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bdb8970b-6645-4cc5-a2e7-e45ff77595f8"),
                            Available = true,
                            Category = "Quarto",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kit completo 400 fios para cama queen.",
                            ImageUrl = "https://images.example.com/jogo-cama.jpg",
                            Price = 329.99m,
                            Title = "Jogo de Cama Queen",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("df173a4e-d8f8-472f-ae72-7b64e3e8f076"),
                            Available = true,
                            Category = "Mesa",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Conjunto de jantar em porcelana branca.",
                            ImageUrl = "https://images.example.com/aparelho-jantar.jpg",
                            Price = 519.00m,
                            Title = "Aparelho de Jantar 20 Peças",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("42fdcc72-664b-4d65-95e2-e8f4f906f28b"),
                            Available = true,
                            Category = "Casa",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Aspirador inteligente com base carregadora.",
                            ImageUrl = "https://images.example.com/aspirador-robo.jpg",
                            Price = 1299.00m,
                            Title = "Aspirador Robô",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("0ac3abdd-0c2d-4234-b72b-b327d8563af7"),
                            Available = true,
                            Category = "Cozinha",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cafeteira automática para cápsulas e pó.",
                            ImageUrl = "https://images.example.com/cafeteira.jpg",
                            Price = 699.90m,
                            Title = "Cafeteira Expresso",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("wedding.gift.Domain.Model.Entities.Contribution", b =>
                {
                    b.HasOne("wedding.gift.Domain.Model.Entities.Gift", "Gift")
                        .WithMany("Contributions")
                        .HasForeignKey("GiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gift");
                });

            modelBuilder.Entity("wedding.gift.Domain.Model.Entities.Gift", b =>
                {
                    b.Navigation("Contributions");
                });
#pragma warning restore 612, 618
        }
    }
}
